### ISSUE TITLE
How to get vehicle_data by BLE

### ISSUE THREAD

**Issue by Whirlwind** [teslamotors/vehicle-command#201] opened 2024-03-04 04:08 UTC
I get the vehicle_data by API, but I want to control the car by BLE ( not wifi )。I must get the current vehicle status, then send the control command。So How to get the current status by BLE? eg: Media、Hvac

**Comment by sethterashima** [comment] 2024-03-08 01:37
Closing as a duplicate of #52

**Closed by sethterashima** 2024-03-08 01:37 UTC
