### ISSUE TITLE
[Feature Request] Can we obtain real-time VCSEC information?

### ISSUE THREAD

**Issue by Whirlwind** [teslamotors/vehicle-command#202] opened 2024-03-04 06:59 UTC
I want to develop a BLE app which can show the current speed and lights status ( eg: turn signal ). Is it possible?

It not uses the Fleet API, so it will not be limited by `Discovery Tier`.

**Comment by sethterashima** [comment] 2024-03-08 01:35
Closing as a duplicate of #52

**Closed by sethterashima** 2024-03-08 01:35 UTC
