### ISSUE TITLE
does sending signed messages work for EU cars

### ISSUE THREAD

**Issue by rawmean** [teslamotors/vehicle-command#32] opened 2023-11-07 00:06 UTC
It seems like the proxy needs the `user_data` scope in order to get the Base URL for the EU region. Is that correct?

Currently, the proxy returns the following error:

`error fetching api/1/vehicles: Get "https://fleetapi-europe.vn.teslamotors.com/api/1/vehicles": dial tcp: lookup fleetapi-europe.vn.teslamotors.com: no such host`

Also, `dig fleetapi-europe.vn.teslamotors.com` does not even resolve:

Trying this: `dig fleetapi-europe.vn.teslamotors.com`

I get this:
```
; <<>> DiG 9.10.6 <<>> fleetapi-europe.vn.teslamotors.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 15016
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
;; QUESTION SECTION:
;fleetapi-europe.vn.teslamotors.com. IN	A

;; AUTHORITY SECTION:
teslamotors.com.	295	IN	SOA	edns69.ultradns.com. soacontact.zoneedit.com. 2013103301 300 3000 86400 300

;; Query time: 27 msec
;; SERVER: redacted
;; WHEN: Mon Nov 06 16:08:21 PST 2023
;; MSG SIZE  rcvd: 135
```

**Comment by RichieB2B** [comment] 2023-11-12 16:34
This seems to be a duplicate of #28

**Comment by rawmean** [comment] 2023-11-17 20:34
This is fixed now

**Closed** 2023-11-17 20:34 UTC
