### ISSUE TITLE
Howto update scopes of partner account?

### ISSUE THREAD

**Issue by andig** [teslamotors/vehicle-command#190] opened 2024-02-19 09:31 UTC
After our application ([evcc.io](https://evcc.io)) has evolved it turns out we'd need the `energy_cmds` scope in addition to what we've setup sofar. Right now we cannot create customer tokens including `energy_cmds` since it's not part of our partner account's scopes.

How can we add new scopes to an existing partner account?

**Comment by DeLN0** [comment] 2024-02-20 18:30
> After our application ([evcc.io](https://evcc.io)) has evolved it turns out we'd need the `energy_cmds` scope in addition to what we've setup sofar. Right now we cannot create customer tokens including `energy_cmds` since it's not part of our partner account's scopes.
> 
> How can we add new scopes to an existing partner account?

I don't think you can do that right now.
A workaround would be to apply for a new app with the same name (with the  correct scopes) in your developer account, then use the client id and client secret from the new app.

**Comment by rkobylinski** [comment] 2024-02-23 09:05
That would be useful. Also removing scopes if it turns out you don't need them (yet?) in production.

**Comment by derekargueta** [comment] 2024-02-26 21:56
This is not yet supported but the feedback is being passed along. Closing as a dupe of https://github.com/teslamotors/vehicle-command/issues/74

**Closed by derekargueta** 2024-02-26 21:56 UTC
